/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hxlin' at '8/11/15 9:00 AM' with Gradle 2.5
 *
 * @author hxlin, @date 8/11/15 9:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
